spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/smartCampus
spring.datasource.username=root
spring.datasource.password=97271
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8087

spring.security.user.name=admin
spring.security.user.password=1234

spring.ai.openai.api-key= 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


